import { StyleSheet, Text, View, ScrollView, Image, Button } from 'react-native'
import React from 'react'
import FooterNav from '../components/FooterNav'
import { useGlobalState } from '../GlobalProvider';
const MyDocument = (props) => {
  const {translation } = useGlobalState();
  return (
    <>
    <ScrollView>
      <View style={styles.main}>
        <Text style={styles.messageText}>{translation.saveAllYourImportantDocumentsHere}</Text>
        <View style={{ paddingBottom:6}}>
        <View style={{flexDirection:"row", justifyContent:"space-between"}}>
            <View style={{alignItems:"flex-end", flexDirection:"row"}}>
                <View>
                <Text style={styles.text}>{translation.cv}</Text>
                <Text style={styles.noteText}>{translation.noteThisIsAnAutoGeneratedCvByOurSystem}</Text>
                </View >
                
            </View>
            <Image source={require("../images/rectangle.png")}/>
        </View>
        <Text  style={styles.blueText}>{translation.clickEditToMakeChanges}</Text>
        </View>
        <View style={styles.buttonBox}>
            <Text style={styles.text}>{translation.passport}</Text>
            <Button title={translation.uploadNow}/>
        </View>
        <View style={styles.buttonBox}>
            <Text style={styles.text}>{translation.experienceCertificate}</Text>
            <Button title={translation.uploadNow}/>
        </View>
        <View style={styles.buttonBox}>
            <Text style={styles.text}>{translation.jobPermit}</Text>
            <Button title={translation.uploadNow}/>
        </View>
        <View style={styles.buttonBox}>
            <Text style={styles.text}>{translation.covidVaccineCertificate}</Text>
            <Button title={translation.uploadNow}/>
        </View>
        <View style={styles.buttonBox}>
            <Text style={styles.text}>{translation.exitLetter}</Text>
            <Button title={translation.uploadNow}/>
        </View>
        <View style={styles.buttonBox}>
            <Text style={styles.text}>{translation.drivingLicense}</Text>
            <Button title={translation.uploadNow}/>
        </View>
        <Text style={styles.text}><Text>+</Text>{translation.addNewDocument}</Text>
        <Text style={styles.grayText}>{translation.allYourDocumentsAreSafeWithUs}</Text>
      </View>
    </ScrollView>
    <FooterNav props={props}/>
      </>
  )
}

export default MyDocument

const styles = StyleSheet.create({
    main: {
        backgroundColor: '#F5F5FA',
        padding: 10,
        marginBottom: 60,
      },
      mainHeading: {
        color: '#0F0C0C',
        fontSize: 16,
        fontWeight: '800',
        fontFamily: 'Nato Sans',
      },
      topNav: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 15,
        marginLeft: -5,
        marginBottom: 30,
      },
      messageText:{
        color: '#0F0C0C',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Nato Sans',
        marginVertical:15
      },
      buttonBox:{
        paddingVertical:17,
        flexDirection:"row",
        justifyContent:"space-between",
        borderTopColor:"#B3B3B3",
        borderTopWidth:1
      },
      text:{
        color: '#000',
        fontSize: 14,
        fontWeight: '400',
        fontFamily: 'Nato Sans',
      },
      noteText:{
        color: '#EB4343',
        fontSize: 10,
        fontWeight: '400',
        fontFamily: 'Nato Sans',
      },
      blueText:{
        color: '#5F90CA',
        fontSize: 10,
        fontWeight: '400',
        fontFamily: 'Nato Sans',
      },
      grayText:{
        textAlign:"center",
        color: '#B3B3B3',
        fontSize: 10,
        fontWeight: '400',
        fontFamily: 'Nato Sans',
        marginVertical:20
      }

})